### ISSUE TITLE
Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'

### ISSUE THREAD

**Issue by buttercubz** [drashland/wocket#113]
using deno 1.7

![image](https://user-images.githubusercontent.com/47539192/105427951-b3cbfb80-5c24-11eb-835d-85c7ce417fd1.png)

**Comment by buttercubz** [comment]
ok seems to work, apparently it was a problem with the cache

**Comment by ebebbington** [comment]
@buttercubz I'd recommend using deno.land or nest.land versioned imports because it can happen that we add a bug into `master`, and your app will fail without you even changing any code:

```
import { Server } from "https://deno.land/x/wocket@v0.6.2/mod.ts"
import { Server } from "https://x.nest.land/wocket@0.6.2/mod.ts"
```

**Comment by buttercubz** [comment]
> @buttercubz I'd recommend using deno.land or nest.land versioned imports because it can happen that we add a bug into `master`, and your app will fail without you even changing any code:
> 
> ```
> import { Server } from "https://deno.land/x/wocket@v0.6.2/mod.ts"
> import { Server } from "https://x.nest.land/wocket@0.6.2/mod.ts"
> ```

oh thanks
