### ISSUE TITLE
Change The Module Name?

### ISSUE THREAD

**Issue by ebebbington** [drashland/wocket#93]
## Summary

What is your question?

Rename the module name, because:

- Obviously "sockets" and "websockets" are different, i think "sockets" would be misleading for the end users
- I think websockets is already taken should we move away from "sockets"
- I think it would be good we iron this stuff out before v1 so it leads to less problems as sockets gets bigger (user base, or feature wise)

Suggestions:

- Ghost (suggested by me), which would make it named after the infamous @saragee3 who built this bad boi of an app
- Wocket (suggested by eric

**Comment by ebebbington** [comment]
We've decided on Wocket. Leaving issue open until all references to the name are changed

**Comment by saragee3** [comment]
Closing! Thanks @ebebbington 👍

**Comment by ebebbington** [comment]
Woop woop!
